### ISSUE TITLE
Add Swadeshi to projects.

### ISSUE THREAD

**Issue by tusharnankani** [HarshKapadia2/web-dev#1]

**Comment by HarshKapadia2** [comment]
To be honest, I didn't include it as I was hardly able to contribute to the project. Most of my code was replaced by @KartikSoneji.

**Comment by tusharnankani** [comment]
Still, I would really like it if you add it to your projects. 

Also, because if we go with that logic, I would feel that the main work was backend, and I actually did nothing.
